package com.myspace.personeriapoc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Document")
public class Document implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	
	private final static String COD_DEP="010";

	@org.kie.api.definition.type.Label(value = "codigoDependencia")
	private java.lang.String codigoDependencia;
	@org.kie.api.definition.type.Label(value = "nombreDocumento")
	private java.lang.String nombreDocumento;
	@org.kie.api.definition.type.Label(value = "tipoDocumento")
	private java.lang.String tipoDocumento;
	@org.kie.api.definition.type.Label(value = "documento")
	private java.lang.String documento;

	public Document() {
	    this.codigoDependencia = COD_DEP;
	}

	public java.lang.String getCodigoDependencia() {
		return this.codigoDependencia;
	}

	public void setCodigoDependencia(java.lang.String codigoDependencia) {
		this.codigoDependencia = codigoDependencia;
	}

	public java.lang.String getNombreDocumento() {
		return this.nombreDocumento;
	}

	public void setNombreDocumento(java.lang.String nombreDocumento) {
		this.nombreDocumento = nombreDocumento;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public java.lang.String getDocumento() {
		return this.documento;
	}

	public void setDocumento(java.lang.String documento) {
		this.documento = documento;
	}

	public Document(java.lang.String codigoDependencia,
			java.lang.String nombreDocumento, java.lang.String tipoDocumento,
			java.lang.String documento) {
		this.codigoDependencia = codigoDependencia;
		this.nombreDocumento = nombreDocumento;
		this.tipoDocumento = tipoDocumento;
		this.documento = documento;
	}

}